<?php
/** @var Magento\Backend\Block\Template $block */

/** @var Bodak\CheckoutCustomForm\Model\Data\CustomFields $customFields */
$customFields = $block->getOrderCustomFields();
?>
<?php if($customFields): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Other information') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="order-information">
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Serial numbers') ?></span>:</strong>
                    <div class="box-content">
                        <input readOnly id="serial_list" type="hidden" disabled="disabled" value="<?php echo $this->escapeHtml($customFields->getCheckoutGoodsMark()); ?>"/>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        requirejs(['jquery','tagify'], function(jQuery, tagify) {
            var input = document.querySelector('#serial_list');
            this.tagifyField = new tagify(input, {
                dropdown: {
                    position: 'text',
                    enabled: 1
                }
            });
        });
    </script>
<?php endif; ?>
