<?php
/** @var Magento\Backend\Block\Template $block */

/** @var Bodak\CheckoutCustomForm\Model\Data\CustomFields $customFields */
$customFields = $block->getOrderCustomFields();
?>
<?php if($customFields): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Other information') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="order-information">
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Device Serial Number') ?></span></strong>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($customFields->getCheckoutSerialNumber()); ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
